### ISSUE TITLE
QR code doesnt resize automatically (receive tab)

### ISSUE THREAD

**Issue by SativaL** [particl/partgui#151] opened 2017-10-08 13:14 UTC
https://media.giphy.com/media/3ov9k4XXBEfHvmLMB2/giphy.gif

shouldnt it be resizing automatically ? this way it looks bugged.

**Comment by rynomster** [comment] 2017-10-08 13:17
Duplicate of #120, fixed in #148

**Closed by rynomster** 2017-10-08 13:17 UTC
