### ISSUE TITLE
Standardise Tray / taskbar behaviour

### ISSUE THREAD

**Issue by rynomster** [particl/partgui#363] opened 2017-11-16 10:07 UTC
# Describe bug/issue

* On OSX, the tray icon is massive, and covers almost the whole top bar, this should be changed to a 16x16 icon.
* We could use the taskbar for the menu instead of the tray, this is standard behavior on OSX apps.
* Not sure if we need to even show the tray icon on OSX.

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Run application on OSX

# More information

- Operating system and version: OSX, any
- Client version: Any electron build / dev electron build

**Comment by HenkSwardt** [comment] 2017-11-16 10:12
Duplicate of #323

**Comment by rynomster** [comment] 2017-11-16 10:32
I don't think its A duplicate.. Maybe a more accurate description, also I believe we should standardize behaviour, consider getting rid of the tray icon on OSX and moving it to the taskbar menu for OSX.

**Closed** 2017-11-30 22:18 UTC
Labels: PRG
