### ISSUE TITLE
encrypting wallet error

### ISSUE THREAD

**Issue by imybb** [particl/partgui#133] opened 2017-09-30 20:55 UTC
WINDOWS - when encrypting wallet for first time, there is an error, screen shots attached
![encrypting_wallet_1](https://user-images.githubusercontent.com/30150617/31049397-0cac1622-a62a-11e7-9f23-6a6e8725a0e7.png)
![encrypting_wallet_2](https://user-images.githubusercontent.com/30150617/31049398-0cc78c90-a62a-11e7-8a6e-c9e3bc9e848f.png)

**Comment by rynomster** [comment] 2017-09-30 21:03
duplicate of #121

**Closed by rynomster** 2017-09-30 21:03 UTC
