### ISSUE TITLE
No notification when receiving a staking reward

### ISSUE THREAD

**Issue by cryptoguard** [particl/partgui#348] opened 2017-11-14 05:09 UTC
The GUI wallet doesn't seem to trigger a notification of received staking reward similar to how particl-qt notifies users with a yellow popup bubble. 

Using Linux Mint XFCE

**Comment by rynomster** [comment] 2017-11-14 05:24
There are now a few notification issues... We are working on it

**Comment by rynomster** [comment] 2017-11-14 05:25
Duplicate of #340

**Closed** 2017-11-14 05:25 UTC
